import { logger } from "../../config/logger";

import { Request, Response, NextFunction } from 'express';
import fs from 'fs';
import path from 'path';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
import crypto from 'crypto';
import { execSync } from 'child_process';
import { isInstalled } from '../../middleware/installGuard';

const apiRoot = path.resolve(__dirname, '../../..');
const lockFilePath = path.resolve(apiRoot, '../.install.lock');
const envFilePath = path.resolve(apiRoot, '../.env');

export class InstallController {
  static getStatus(req: Request, res: Response, next: NextFunction) {
    try {
      res.json({ success: true, data: { installed: isInstalled() } });
    } catch (error) {
      next(error);
    }
  }

  static async checkDb(req: Request, res: Response, next: NextFunction) {
    let tempPrisma: PrismaClient | null = null;
    try {
      const { databaseUrl } = req.body;
      if (!databaseUrl) {
        return res.status(400).json({ success: false, error: { message: 'Database URL is required' } });
      }

      tempPrisma = new PrismaClient({
        datasourceUrl: databaseUrl,
      });

      await tempPrisma.$connect();
      await tempPrisma.$queryRaw`SELECT 1`;

      res.json({ success: true, data: { message: 'Database connection successful' } });
    } catch (error: any) {
      res.status(400).json({ success: false, error: { message: error.message || 'Failed to connect to database' } });
    } finally {
      if (tempPrisma) {
        await tempPrisma.$disconnect().catch(() => {});
      }
    }
  }

  static async setup(req: Request, res: Response, next: NextFunction) {
    try {
      if (isInstalled()) {
        return res.status(403).json({ success: false, error: { message: 'Already installed' } });
      }

      const {
        databaseUrl,
        appName,
        appUrl,
        adminName,
        adminEmail,
        adminPassword
      } = req.body;

      if (!databaseUrl || !adminEmail || !adminPassword) {
         return res.status(400).json({ success: false, error: { message: 'Missing required fields' } });
      }

      const jwtSecret = crypto.randomBytes(32).toString('hex');
      const encryptionKey = crypto.randomBytes(16).toString('hex'); // 32 characters
      const adminSessionSecret = crypto.randomBytes(32).toString('hex');

      const envContent = `
# Generated by Installer
NODE_ENV=production
PORT=4000
APP_NAME="${appName || 'DirectorByte'}"
APP_URL="${appUrl || 'http://localhost:3000'}"
API_URL="${appUrl ? appUrl.replace('3000', '4000') : 'http://localhost:4000'}"
DATABASE_URL="${databaseUrl}"
REDIS_URL="redis://localhost:6379"

JWT_SECRET="${jwtSecret}"
JWT_ACCESS_EXPIRY="15m"
JWT_REFRESH_EXPIRY="30d"
ENCRYPTION_KEY="${encryptionKey}"
ADMIN_SESSION_SECRET="${adminSessionSecret}"

SMTP_PORT=587
SMTP_SECURE=false
EMAIL_FROM_NAME="${appName || 'DirectorByte'}"
STORAGE_PROVIDER="local"
LOCAL_UPLOAD_PATH="./uploads"
MAX_UPLOAD_SIZE_MB=100
      `.trim() + '\n';

      // 1. Write .env file
      fs.writeFileSync(envFilePath, envContent);

      // We need to inject the newly generated DATABASE_URL into the current process so Prisma can migrate
      process.env.DATABASE_URL = databaseUrl;

      // 2. Run migrations
      try {
        logger.info('Running migrations...');
        execSync('npx prisma migrate deploy', {
          stdio: 'inherit',
          cwd: apiRoot // apps/api dir
        });
        logger.info('Migrations complete.');
      } catch (err: any) {
        return res.status(500).json({ success: false, error: { message: 'Database migration failed: ' + (err.message || 'Unknown error') } });
      }

      // 3. Create Super Admin
      const setupPrisma = new PrismaClient({ datasourceUrl: databaseUrl });
      await setupPrisma.$connect();

      try {
        const existingAdmins = await setupPrisma.user.count({
          where: { role: 'ADMIN' } // using ADMIN enum as it maps to string, wait, schema is UserRole.ADMIN
        });

        if (existingAdmins === 0) {
          const passwordHash = await bcrypt.hash(adminPassword, 10);
          await setupPrisma.user.create({
            data: {
              email: adminEmail,
              displayName: adminName || 'Super Admin',
              passwordHash,
              role: 'ADMIN',
              status: 'ACTIVE',
              emailVerified: true
            }
          });
        }
      } catch (err: any) {
         await setupPrisma.$disconnect();
         return res.status(500).json({ success: false, error: { message: 'Failed to create admin user: ' + (err.message || 'Unknown error') } });
      }

      await setupPrisma.$disconnect();

      // 4. Lock installation
      fs.writeFileSync(lockFilePath, new Date().toISOString());

      res.json({ success: true, data: { message: 'Installation complete. Restarting...' } });

      // 5. Restart process
      setTimeout(() => {
        process.exit(0);
      }, 1000);

    } catch (error: any) {
      next(error);
    }
  }

  static async disable(req: Request, res: Response, next: NextFunction) {
    try {
      if (!isInstalled()) {
        fs.writeFileSync(lockFilePath, new Date().toISOString());
      }
      res.json({ success: true });
    } catch (error) {
      next(error);
    }
  }
}
